name: Dev Workflow

on:
  push:
    paths:
    - "envs/dev/**"
    - "modules/**"

  workflow_dispatch:

env:
  TERRAFORM_VERSION: "1.15.8"
  PYTHON_VERSION: "3.14"

defaults:
  run:
    working-directory: ./envs/dev

jobs:
  python-unit-test:
    name: Python Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies
      run: pip install -r requirements.txt
      working-directory: ./modules/lambda

    - name: Run Python unit tests
      run: python -m unittest
      working-directory: ./modules/lambda/tests

  deploying-to-localstack:
    name: Deploying to LocalStack
    needs: python-unit-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Start LocalStack
      uses: LocalStack/setup-localstack@19cb04b7695736b30be27d4673d721086f5d1748
      with:
        image-tag: 'latest'
      env:
        LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Set up tflocal
      run: pip install terraform-local

    - name: Running tflocal init
      run: tflocal init

    - name: Running tflocal plan
      run: tflocal plan -var-file=dev.tfvars

    - name: Running tflocal apply
      run: tflocal apply -var-file=dev.tfvars -auto-approve
      continue-on-error: true # This is allow the workflow to still succeed, and not fail due to not having a LocalStack subscription to deploy an eventbridge pipe